image: node:8
pipelines:
  default:
    - step:
        name: build
        script:
          - npm install
          - npm install -g jest
    - step:
        name: build and test
        script:
          - npm install
          - npm install -g jest
          - jest